<!DOCTYPE html>
<html lang="fr"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Francis Duval, Chercheur Scientifique | Recherche et Innovation Analytique">
  <title>L’intelligence d’affaires chez Co-operators</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-28eafc3999ee829c375161a4b622e95f.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block title-slide-theme-1 center">
  <h1 class="title">L’intelligence d’affaires chez Co-operators</h1>
  <p class="subtitle">Présentation dans le cadre du cours « Applications probabilistes des risques actuariels »</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Francis Duval, Chercheur Scientifique | Recherche et Innovation Analytique 
</div>
<div class="quarto-title-author-email">
<a href="mailto:francis_duval@cooperators.ca">francis_duval@cooperators.ca</a>
</div>
</div>
</div>

  <p class="date">7 octobre 2025</p>

</section>
<section id="mon-parcours" class="slide level2">
<h2>Mon parcours</h2>
<h3 id="académique">Académique</h3>
<div class="columns">
<div class="column" style="width:33%;">
<p><span class="three-green-blocks">Baccalauréat</span></p>
<div style="height:70px;">

</div>
<div class="ul-font-size-small">
<ul>
<li><strong>Actuariat</strong></li>
<li>2 stages chez Intact</li>
<li>Session à l’étranger à Lyon</li>
</ul>
</div>
</div><div class="column" style="width:33%;">
<p><span class="three-green-blocks">Maitrise</span></p>
<div style="height:70px;">

</div>
<div class="ul-font-size-small">
<ul>
<li><strong>Mathématiques actuarielles et financières</strong></li>
<li>Mémoire: Techniques de gradient boosting pour la modélisation des réserves individuelles en assurance non-vie</li>
<li>Stage de recherche Mitacs chez Desjardins</li>
</ul>
</div>
</div><div class="column" style="width:33%;">
<p><span class="three-green-blocks">Doctorat</span></p>
<div style="height:70px;">

</div>
<div class="ul-font-size-small">
<ul>
<li><strong>Mathématiques</strong></li>
<li>Thèse: Modélisation des sinistres en assurance automobile avec l’utilisation de données télématiques : approches d’apprentissage automatique en classification et régression de comptage</li>
<li>Chaire Co-operators en analyse des risques actuariels</li>
</ul>
</div>
</div></div>
<h3 id="professionel">Professionel</h3>
<ul>
<li>Chercheur scientifique dans l’équipe « Recherche et Innovation Analytique » depuis septembre 2023.</li>
</ul>
<aside class="notes">
<ul>
<li><p>Baccalauréat en Actuariat, où j’ai eu 2 stages en assurance de dommages chez Intact.</p></li>
<li><p>Session à l’étranger à l’Institut de Science Financière et d’Assurance (ISFA).</p></li>
<li><p>Ensuite, j’ai fait une maitrise en mathématiques actuarielles et financière, toujours à l’UQAM.</p></li>
<li><p>J’ai eu la chance durant ma maitrise de faire un stage de recherche Mitacs chez Desjardins. Mitacs est un organisme de recherche sans but lucratif qui offre des bourses de recherche, notamment pour des stages en entreprise.</p></li>
<li><p>Durant ce stage chez Desjardins, j’ai développé un modèle d’évaluation des réserves en utilisant un algorithme de gradient boosting. C’est un modèle de réserve au niveau individuel, c’est-à-dire que contrairement à des modèles comme Chain-Ladder, on a essayer de prédire un montant pour chaque réclamation, de manière individuelle.</p></li>
<li><p>Ce qui était bien avec ce stage, c’est que le modèle que j’ai développé a servi pour mon mémoire de maitrise, et j’ai même publié un article avec Mathieu Pigeon. Donc c’est faire d’une pierre deux coups.</p></li>
<li><p>Suite à ma maitrise, j’ai eu une offre de Jean-Philippe et Mathieu Pigeon pour continuer mes études au sein de la Chaire CARA, qui venait tout juste d’être mise sur pieds. Comme j’avais aimé mon expérience de recherche à la maitrise, et que je trouvais que l’UQAM offrait une solide expertise en assurance de dommages avec des professeurs comme Jean-Philippe et Mathieu en plus du partenariat avec Co-operators, j’ai décidé de commencer un doctorat. De plus, le financement était excellent.</p></li>
<li><p>J’ai fait ce qu’on appelle une thèse par article, qui consiste en 3 articles sur le même thème. Les articles sont ensuite mis ensemble pour constituer la thèse.</p></li>
<li><p>Ma thèse portait sur la modélisation des sinistres en assurance automobile avec des méthodes de machine learning utilisant des données télématiques.</p></li>
<li><p>Et depuis maintenant 2 ans, je suis chercheur scientifique dans l’équipe de Recherche et Innovation Analytique chez Co-operators, où j’ai déjà eu l’occasion de travailler sur plusieurs projets.</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="introduction-à-lassurance-de-dommages-lintelligence-daffaires-et-co-operators" class="title-slide slide level1 center">
<h1>1. Introduction à l’assurance de dommages, l’intelligence d’affaires, et Co-operators</h1>

</section>
<section id="assurance-de-dommage" class="slide level2">
<h2>Assurance de dommage</h2>
<ul>
<li>Aussi appelée « assurance IARD » (Incendie, Accidents et Risques Divers) c’est un type d’assurance qui protège les <strong>individus</strong> et les <strong>entreprises</strong> contre les pertes financières liées à leurs <strong>biens</strong> et à leur <strong>responsabilité</strong> pour les dommages qu’ils peuvent causer à autrui.</li>
<li>En anglais, <strong>Property &amp; Casualty (P&amp;C) insurance</strong> (property = « biens », casualty = « responsabilité »).</li>
</ul>
<div style="height:30px;">

</div>
<div class="columns">
<div class="column" style="width:48%;">
<p><span class="two-blue-blocks">Biens</span></p>
<div style="height:70px;">

</div>
<div class="ul-font-size-medium">
<ul>
<li>Assurance habitation: protège contre les incendies, vols, catastrophes naturelles, etc.</li>
<li>Assurance automobile: protège contre les dommages au véhicule pour collision, incendies, vols, vandalisme, etc.</li>
<li>Assurance de biens commerciaux: protège le bâtiment, le contenu, etc.</li>
</ul>
</div>
</div><div class="column" style="width:48%;">
<p><span class="two-blue-blocks">Responsabilité</span></p>
<div style="height:70px;">

</div>
<div style="padding-left:0px;">
<div class="ul-font-size-medium">
<ul>
<li>Assurance responsabilité civile: protège contre la responsabilité pour les blessures ou les dommages qu’ils peuvent causer à autrui</li>
</ul>
</div>
</div>
</div></div>
<aside class="notes">
<ul>
<li>En gros, l’assurance de dommages est tout ce qui n’est pas de l’assurance vie ni de l’assurance collective!</li>
<li>Aussi appelée « assurance IARD », ou « property &amp; casualty » en anglais.</li>
<li>Le property, c’est pour les biens. Donc l’assurance de n’importe quel objet appartenant à l’assuré, que ce soit une voiture, une maison, etc.</li>
<li>Le casualty, c’est la responsabilité. Ça protège contre la responsabilité pour les blessures ou les dommages causé à autrui.</li>
<li>Par exemple, vous êtes obligé, lorsque vous conduisez une voiture au Québec, d’avoir une assurance responsabilité civile. Ça vous protège lorsque vous avez un accident responsable et que vous avez causé des blessures à quelqu’un ou des dommages à ses biens.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="assurance-de-dommage-1" class="slide level2">
<h2>Assurance de dommage</h2>
<h3 id="quest-ce-quon-fait-en-assurance-de-dommage">Qu’est-ce qu’on fait en assurance de dommage?</h3>
<div class="columns">
<div class="column" style="width:48%;">
<p><span class="two-green-blocks">Rôles « traditionnels »</span></p>
<div style="height:70px;">

</div>
<ul>
<li>Tarification
<ul>
<li>Indiqués</li>
<li>Segmentation</li>
</ul></li>
<li>Évaluation des réserves
<ul>
<li>IBNR (<em>Incurred But Not Reported</em>)</li>
<li>RBNS (<em>Reported But Not Settled</em>)</li>
</ul></li>
<li>Réassurance</li>
</ul>
</div><div class="column" style="width:48%;">
<p><span class="two-green-blocks">Rôles « non-traditionnels »</span></p>
<div style="height:70px;">

</div>
<div style="padding-left:0px;">
<ul>
<li>Intelligence d’affaires</li>
<li>Analytique des réclamations</li>
<li>Analytique de la souscription</li>
</ul>
</div>
</div></div>
<aside class="notes">
<ul>
<li><p>Les rôles peuvent être séparés en rôles traditionnels et non-traditionnels.</p></li>
<li><p>Les rôles traditionnels sont ceux qu’on associe plus naturellement au mot « actuariat ».</p></li>
<li><p>Les rôles traditionnels sont le plus souvent occupés par des actuaires, tandis que les rôles non-traditionnels peuvent être occupés par des actuaires, mais aussi par des scientifiques de donnnées, des programmeurs, etc.</p></li>
<li><p>Dans les rôles traditionnels, on a la tarification, qui se sépare en 2 tâches. La première sont les indiqués (<em>rate indication</em>), où il faut estimer le montant total des réclamations qu’on aura à payer l’an prochain. Ça sert à déterminer le pourcentage d’augmentation globale des taux.</p></li>
<li><p>La deuxième tâche est la segmentation, qui consiste à évaluer le risque associé à chaque groupe d’assurés pour fixer des primes d’assurance qui réflète leur niveau de risque. Cette étape est importante pour contrer l’anti-sélection.</p></li>
<li><p>On a aussi l’évaluation des réserves. Ça consiste à estimer le montant à mettre de côté pour des réclamations qui sont arrivées mais qui n’ont pas été encore reportée à l’assureur, ou bien pour des réclamations qui sont reportées mais pas encore fermées.</p></li>
<li><p>Ensuite, on a la réassurance. Par exemple, on doit s’assurer qu’on est capable de payer les réclamations en cas de catastrophe (par exemple, une catastrophe naturelle comme une inondation). Sinon, on devra peut-être revoir nos contrats de réassurance.</p></li>
<li><p>Ensuite, il y a les rôles « non-traditionnels ».</p></li>
<li><p>Ce sont des rôles où typiquement, la programmation est plus ominprésente. Chez Co-operators, on utilise beaucoup R et Python.</p></li>
<li><p>Ce sont des rôles qui sont moins « actuariels », mais qui peuvent quand même être occupés par des actuaires, étant donné qu’ils ont une bonne expertise en statistiques, en programmation.</p></li>
<li><p>Parmi ces rôles, on a l’intelligence d’affaires, l’analytique des réclamations et l’analytique de la souscription.</p></li>
<li><p>Je dirais que l’analytique des réclamations et l’analytique de la souscription, ça ressemble beaucoup à l’intelligence d’affaires, sauf que c’est plus axé sur optimiser le processus des réclamations et de la souscription.</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="co-operators" class="slide level2">
<h2>Co-operators</h2>
<ul>
<li>Coopérative d’assurance de dommage fondée en 1945 par un groupe de fermiers 🧑‍🌾</li>
</ul>
<p><strong>Notre mission</strong></p>
<ul>
<li>Assurer la sécurité financière des Canadiennes et Canadiens et de nos collectivités. Parce que nous sommes une coopérative, nos décisions d’affaires sont guidées par nos valeurs d’inclusion et de développement durable et responsable.</li>
</ul>
<p><strong>Exemples d’engagements concrets</strong></p>
<ul>
<li>Investissements dans des fonds verts🌳💰</li>
<li>Assurance innondation🌊</li>
<li>Programme « Build Back Better »🏗️</li>
<li>Programme de séchage lors de dégâts d’eau spécifiques💧</li>
</ul>
<!-- ![](images/auto.svg){.absolute width=200 top=450 left=0} -->
<!-- ![](images/maison.svg){.absolute width=200 top=450 left=200} -->
<!-- ![](images/entreprise.svg){.absolute width=200 top=450 left=600} -->
<!-- ![](images/ferme.svg){.absolute width=200 top=450 left=800} -->
<!-- [Lignes personnelles]{.absolute top=650 left=100} -->
<!-- [Lignes commerciales]{.absolute top=650 left=700} -->
<aside class="notes">
<ul>
<li><p>Co-operators, c’est une coopérative d’assurance de dommage fondée en 1945 par un groupe de fermiers qui ne trouvaient pas de produit d’assurance convenable pour leurs fermes.</p></li>
<li><p>Exemple de développement durable et responsable:</p>
<ul>
<li>Investissement dans des fonds verts.</li>
<li>Programme de « Séchage » lors de dégâts d’eau spécifiques.</li>
<li>Assurance que les autres assureurs n’offrent pas: inondations.</li>
<li>Programme « Build Back Better »: dans certains cas comme les tempêtes de grêles, on s’engage à rebâtir avec des matériaux résistants à une prochaine tempête. On assume le cout additionel de reconstruction.</li>
</ul></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="quest-ce-que-lintelligence-daffaires" class="slide level2">
<h2>Qu’est-ce que l’intelligence d’affaires?</h2>
<h3 id="intelligence-daffaires-tirer-de-la-valeur-des-données">Intelligence d’affaires = Tirer de la valeur des données</h3>
<p>Les données ne parlent pas d’elles-mêmes: il faut les faire parler.</p>
<p><br></p>
<div class="columns">
<div class="column" style="width:48%;">
<p><span class="two-blue-blocks">Avec…</span></p>
<div style="height:70px;">

</div>
<ul>
<li>Programmation R/Python (et autres)</li>
<li>Machine learning/Deep learning</li>
<li>Traitement de langage naturel</li>
<li>Théorie des valeurs extrêmes</li>
<li>Modèles de catastrophes</li>
<li>Modèles statistiques classiques</li>
<li>Etc.</li>
</ul>
</div><div class="column" style="width:48%;">
<p><span class="two-blue-blocks">…on produit</span></p>
<div style="height:70px;">

</div>
<div style="padding-left:0px;">
<ul>
<li>Modèles</li>
<li>Tableaux de bord</li>
<li>Applications Shiny (ou autre)</li>
<li>Visualisations</li>
<li>Analyses statistiques</li>
<li>Etc.</li>
</ul>
</div>
</div></div>
<p><img data-src="images/dashboard.png" class="absolute" style="top: 0px; right: 0px; width: 200px; "></p>
<aside class="notes">
<ul>
<li>2 grands départements chez Co-operators: Actuariat et Intelligence d’Affaires. Qu’est-ce que l’intelligence d’affaires exactement?</li>
<li>La mission du département d’intelligence d’affaire est de tirer le plus de valeur possible des données.</li>
<li>Les données peuvent être sous n’importe quelle forme: données tabulaires, données textuelles, données temporelles, données d’images, données géospatiales, données audio, etc.</li>
<li>Par contre, les données ne parlent pas d’elles-mêmes. Par exemple, on peut difficilement tirer des conclusions en observant à l’oeil une table de données. Il faut donc les faire « parler » en utilisant tous les moyens possibles: programmation, machine learning, deep learning, IA, théorie des valeurs extrêmes, et plusieurs autres modèles de toute sorte.</li>
<li>On produit alors des outils qui nous aident à tirer profit des données et de prendre les bonnes décisions, comme des modèles, des applications, des tableaux de bord, des visualisations, etc.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="exemple-de-projet" class="title-slide slide level1 center">
<h1>2. Exemple de projet</h1>
<aside class="notes">
<ul>
<li>Maintenant, je vais vous parler d’un projet que j’ai fait dans l’équipe de recherche. C’est en fait le premier projet qui m’a été assigné quand j’ai commencé à tavailler.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h4 id="problème-à-résoudre-en-assurance-commerciale">Problème à résoudre en assurance commerciale</h4>
<div class="ul-font-size-small">
<ul>
<li>Lorsqu’on souscrit une police d’assurance commerciale, on doit lui assigner un code parmi 1260 codes. Étant donnée une description d’entreprise, on doit assigner le bon code.</li>
<li>Par exemple, quel code doit-on assigner à l’entreprise décrite par <span style="color: #FFFFFF; background-color: #007d57; border-radius: 5px; padding: 2px 5px;">Small place where they serve coffee and food such as pastries</span>?</li>
</ul>
</div>
<div class="fragment fade-in">
<h4 id="données">Données</h4>
</div>
<div class="fragment fade-in-then-out">
<div style="font-size: 25px; position: absolute; top: 315px; left: 0px;">
<p>IBC Codes</p>
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 28%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Index</th>
<th>IBC Code</th>
<th>IBC Code Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0735a10</td>
<td>Architects - Landscaping Only</td>
</tr>
<tr class="even">
<td>2</td>
<td>8916a10</td>
<td>Engineers</td>
</tr>
<tr class="odd">
<td>3</td>
<td>8075a10</td>
<td>Sanitariums</td>
</tr>
<tr class="even">
<td>4</td>
<td>5813a10</td>
<td>Coffee shops (warming of food only, no roasting of beans)</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>1260</td>
<td>3496a10</td>
<td>Electronic games</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment fade-in">
<div style="font-size: 25px; position: absolute; top: 315px; left: 0px;">
<p>Entreprises</p>
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 44%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Index</th>
<th>Company Description</th>
<th>IBC Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Takeout meals-see policy, coding only</td>
<td>5814a10 – Take out meals</td>
</tr>
<tr class="even">
<td>2</td>
<td>Construction of church building extension</td>
<td>1830a20 – Building construction - general contr.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Construction and renovation of gas stations including installation and removal of underground tanks and related pumps, carwash facilities. Snow clearing.</td>
<td>1782a40 – Underground storage tank - remediation contractors</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>136 000</td>
<td>Licensed Restaurant</td>
<td>5812a10 – Restaurants - licensed (Not liquor revenue)</td>
</tr>
</tbody>
</table>
</div>
</div>
<aside class="notes">
<ul>
<li><p>Je vous explique ici quel était le problème à résoudre.</p></li>
<li><p>On est dans le contexte de l’assurance commerciale, donc l’assurance d’entreprises.</p></li>
<li><p>Lorsqu’on assure une entreprise, le souscripteur doit lui assigner un code IBC parmi 1260 codes, ce qui n’est pas toujours évident parce qu’il y a beaucoup de codes, certains codes se ressemblent, et certains sont assez obscurs.</p></li>
<li><p>Le mandat était de créer un outil de suggestion de codes qui permet de faciliter la tâche du souscripteur.</p></li>
<li><p>Ce qu’on a fait en gros, c’est qu’on a pris un modèle de langage pré-entrainé qu’on a fine-tuné sur nos données. On a ensuite développé un modèle de classification à partir de ce modèle de language, et on a emballé le tout dans une application Shiny facile d’utilisation.</p></li>
<li><p>J’avais 2 jeux de données à ma disposition. Le premier contient tous les codes et leur description.</p></li>
<li><p>Ce sont des codes qui représente des secteurs de l’industrie.</p></li>
<li><p>Le deuxième contient 136 000 entreprises qu’on a assurées dans le passé avec leur code IBC associé.</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-1" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h4 id="embeddings-encoder-une-phrase-ou-un-mot-avec-un-vecteur-de-nombres-réels">Embeddings = Encoder une phrase (ou un mot) avec un vecteur de nombres réels</h4>

<img data-src="images/embeddings.jpg" class="r-stretch"><p>Les mots/phrases similaires doivent être proches dans l’espace d’embedding.</p>
<aside class="notes">
<ul>
<li>Le modèle de langage qu’on a utilisé (comme beaucoup d’autres modèles de langage) est un modèle d’embedding.</li>
<li>C’est quoi un embedding? C’est simplement une chaine de caractères encodée sous forme d’un vecteur.</li>
<li>Ça peut être n’importe quelle chaine de caractères: un mot, une phrase, un document, etc.</li>
<li>Donc un modèle d’embedding, c’est un modèle qui permet de transformer du texte en nombres.</li>
<li>Important parce qu’un ordinateur ne peut pas traiter du texte, seulement des nombres.</li>
<li>Un modèle d’embedding, c’est une fonction qui prend en entrée du texte et qui renvoie un vecteur en n dimensions.</li>
<li>Et comme vous le savez, un vecteur en n dimensions définit un point dans un espace en n dimensions qu’on appelle l’espace d’embedding.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-2" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h3 id="espace-dembedding">Espace d’embedding</h3>
<ul>
<li>Un bon modèle d’embedding va positionner les mots (ou phrases) de sens similaire « près » les uns des autres dans l’espace d’embedding.</li>
<li>Dans cet exemple, nous avons un embedding en 2 dimensions, mais en pratique, les embeddings possèdent généralement un nombre beaucoup plus élevé de dimensions.</li>
</ul>

<img data-src="images/embeddings_2.png" class="r-stretch"><aside class="notes">
<ul>
<li>Un bon modèle d’embeddings, c’est un modèle qui va placer des mots (ou des chaines de caractères) de sens similaire proches dans l’espace d’embeddings. À l’inverse, les mots de sens non-similaire doivent être éloignés.</li>
<li>Ici par exemple, on a obtenu un embedding en 2D pour les mots « roi », « reine », « pomme » et « banane ».</li>
<li>On voit que les embeddings créés semblent avoir du sens puisque « roi » et « reine », qui ont des sens similaires, sont proches dans l’espace d’embedding. Les embeddings de « pomme » et « banane » sont également proches, tandis que les 2 fruits et les 2 personnes sont éloignés.</li>
<li>Ici embedding très simple en 2D mais habituellement, on a beaucoup plus de dimensions que ça.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-3" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h3 id="interprétation-des-dimensions">« Interprétation » des dimensions</h3>
<p><br> <br> <br> <br></p>
<ul>
<li>Les valeurs des embeddings peuvent être imaginées étant des « concepts ».</li>
<li>Par exemple, une des dimensions pourraient être le degré de « félinité ».</li>
<li>En pratique, ces concepts sont obscures et pas humainement identifiables.</li>
</ul>
<p><img data-src="images/embeddings_as_concepts.png" class="absolute" style="top: 100px; right: 0px; "></p>
<aside class="notes">
<ul>
<li>On peut avoir une pseudo-interprétation pour les dimensions des embeddings.</li>
<li>Donc ici, on a des embeddings en 7 dimensions de plusieurs mots, et on peut s’imaginer que chaque dimension correspond à un concept.</li>
<li>Donc on peut s’imaginer que la dimension 1 correspond au degré de « vie », la dimension 2 correspond au degré de « félinité », la troisième au degré d’humanité, etc.</li>
<li>Par exemple, le chat et le chaton ont un haut degré de félinité, tandis que la maison a un faible degré de félinité.</li>
<li>En pratique par contre, on ne peut pas vraiment associer chaque dimension à un concept qu’on peut interpréter.</li>
<li>Par contre, ça reste que chaque dimension est associée à un concept dont le modèle peut utiliser.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-4" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h3 id="bert-fournit-des-embeddings-de-mots-contextualisés-de-haute-qualité">BERT: fournit des embeddings de mots contextualisés de haute qualité</h3>
<p><img data-src="images/bert_puppet.png" class="absolute" style="top: 164px; right: 30px; width: 350px; "></p>
<div width="100%">
<p><br></p>
<ul>
<li>BERT: <strong>B</strong>idirectional <strong>E</strong>ncoder <strong>R</strong>epresentations from <strong>T</strong>ransformers</li>
<li>Développé par <strong><span style="color:#174EA6;">G</span><span style="color:#A50E0E;">o</span><span style="color:#FBBC04;">o</span><span style="color:#174EA6;">g</span><span style="color:#0D652D;">l</span><span style="color:#A50E0E;">e</span></strong> en 2018</li>
</ul>
</div>
<p><br></p>
<div class="columns">
<div class="column" style="width:33%;">
<p><span class="three-green-blocks">Pré-entrainé sur beaucoup de texte</span></p>
<div style="height:70px;">

</div>
<div class="ul-font-size-small">
<ul>
<li>BERT base: BooksCorpus (~800M mots)<br>
</li>
<li>BERT large: Wikipédia anglais (~2500M mots)</li>
<li>Permet d’obtenir de bonnes performances même sans fine-tuning</li>
</ul>
</div>
</div><div class="column" style="width:33%;">
<p><span class="three-green-blocks">Embeddings contextualisés</span></p>
<div style="height:70px;">

</div>
<div class="ul-font-size-small">
<ul>
<li>Contexte bidirectionnel<br>
</li>
<li>D’anciens modèles comme Word2Vec et GloVe ne prenaient pas du tout en compte le contexte</li>
</ul>
</div>
</div><div class="column" style="width:33%;">
<p><span class="three-green-blocks">Open-source</span></p>
<div style="height:70px;">

</div>
<div class="ul-font-size-small">
<ul>
<li>On peut le télécharger gratuitement sur <a href="HuggingFace.co">HuggingFace.co</a></li>
<li>On peut le fine-tuner sur une tâche particulière</li>
</ul>
</div>
</div></div>
<aside class="notes">
<ul>
<li><p>Le modèle qui sert de base à notre modèle d’embedding de phrases s’appelle BERT.</p></li>
<li><p>C’est un modèle d’embeddings qui a été développé par Google.</p></li>
<li><p>C’est un modèle assez puissant pour 2 raisons principales.</p></li>
<li><p>Premièrement, il a été pré-entrainé sur énormément de texte (sur plus de 3 milliards de mots), ce qui fait qu’il peut être utilisé directement sans être fine-tuné.</p></li>
<li><p>Deuxièmement, c’est un modèle basé sur l’architecture transformer, qui permet d’obtenir des embeddings contextualisés de haute qualité, tout en étant hautement paraléllisable.</p></li>
<li><p>C’est un modèle open-source, donc n’importe qui peut le télécharger et l’utiliser directement, ou bien le fine-tuner sur une tâche particulière.</p></li>
<li><p>J’ajouterais également que BERT est relativement léger avec ses 110 millions de paramètres pour la version de base, ce qui permet de rapidement obtenir des embeddings, même sur un laptop.</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-5" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Pré-entrainement</strong><br>
<img data-src="images/pretraining.png" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</div><div class="column" style="width:50%;">
<p><strong>Fine-tuning</strong><br>
<img data-src="images/finetuning.png" class="quarto-figure quarto-figure-center" style="width:78.0%"></p>
</div></div>
<aside class="notes">
<ul>
<li><p>Donc je vous ai parlé de pré-entrainement et de fine-tuning. À quoi ça correspond exactement?</p></li>
<li><p>Le pré-entrainement, ça se résume à faire apprendre la langue au modèle. Donc les patterns de la langue, la grammaire, la syntaxe, etc.</p></li>
<li><p>Pour ce faire, on va entrainer le modèle sur des grandes quantités de texte. Donc par exemple, sur Wikipédia au grand complet.</p></li>
<li><p>Et pour BERT, la méthode utilisée pour le pré-entrainer s’appelle <em>masked language modeling</em>. Ça consiste à cacher certain mots au modèle de manière aléatoire, et on demande au modèle de deviner le mot. On a ensuite une fonction de perte qui va punir le modèle pour ses erreurs, et avec la rétro-propagation et la descente de gradient, on peut aller mettre à jour les poids du modèle.</p></li>
<li><p>On peut utiliser le modèle pré-entrainé directement, mais on va avoir de meilleures performances si on le fine-tune sur notre tâche à accomplir.</p></li>
<li><p>Donc dans l’étape du fine-tuning, on prend le modèel pré-entrainé et on l’entraine de nouveau sur notre jeu de données.</p></li>
<li><p>Par exemple, ici on a fine-tuné BERT sur une tâche de classification de courriels (pourriel ou courriel légitime).</p></li>
<li><p>On a ajouté une tête de classification au modèle, qui permet de transformer la sortie de BERT en probabilité d’être un pourriel.</p></li>
<li><p>On va ensuite aller faire l’entrainement en utilisant un jeu de données de courriels étiquetés « spam » ou « not-spam ».</p></li>
<li><p>Donc en gros, dans cette étape de fine-tuning, les poids du modèle vont être modifiés de telle sorte que la tâche à accomplir est optimisée.</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-6" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h3 id="fine-tuner-le-modèle-pré-entrainé">Fine-tuner le modèle pré-entrainé</h3>
<p>On génère d’abord des <span style="color: #007d57;"><strong>paires positives</strong></span> et des <span style="color: #650b22;"><strong>paires négatives</strong></span>.</p>
<div class="ul-font-size-medium">
<ul>
<li><span style="color: #007d57;"><strong>paire positive</strong></span>: description de l’entreprise + description de son IBC code <span style="color: #007d57;"><strong>correspondant</strong></span></li>
<li><span style="color: #650b22;"><strong>paire négative</strong></span>: description de l’entreprise + description d’un IBC code <span style="color: #650b22;"><strong>non-correspondant</strong></span></li>
</ul>
</div>
<div style="font-size: 24px;">
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Pair ID</th>
<th>Company Description</th>
<th>IBC Code Description</th>
<th>Label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Construction of church building extension</td>
<td>Building construction - general contr.</td>
<td><span style="color: #007d57;"><strong>Positive pair</strong></span></td>
</tr>
<tr class="even">
<td>2</td>
<td>Construction of church building extension</td>
<td>Take out meals</td>
<td><span style="color: #650b22;"><strong>Negative pair</strong></span></td>
</tr>
<tr class="odd">
<td>3</td>
<td>Licensed restaurant</td>
<td>Restaurants - licensed (Not liquor revenue)</td>
<td><span style="color: #007d57;"><strong>Positive pair</strong></span></td>
</tr>
<tr class="even">
<td>4</td>
<td>Licensed restaurant</td>
<td>Building construction - general contr.</td>
<td><span style="color: #650b22;"><strong>Negative pair</strong></span></td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
</tbody>
</table>
</div>
<p>On va ensuite entrainer le modèle à rapprocher les <span style="color: #007d57;"><strong>paires positives</strong></span> et à éloigner les <span style="color: #650b22;"><strong>paires négatives</strong></span> en utilisant une fonction de perte et la descente de gradient.</p>
<aside class="notes">
<ul>
<li>La première étape est de se créer un jeu de données étiqueté. On va se créer autant de paires positives que de paires négatives.</li>
<li>Une paire positive, c’est une description d’entreprise couplée avec la description de son code IBC correspondant.</li>
<li>Une paire négative, c’est une description d’entreprise couplée avec une description de code IBC non-correspondant.</li>
<li>L’algorithme d’entrainement est alors déclenché pour modifier les paramètres du modèle de telle sorte que les entreprises sont rapprochées de leur IBC code correspondant (et éloignées de leurs codes IBC non-correspondants).</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-7" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h3 id="fonctionnement-du-modèle">Fonctionnement du modèle</h3>
<p>Partons avec cette description d’entreprise cible: <br> <span style="color: #FFFFFF; background-color: #007d57; border-radius: 5px; padding: 2px 5px;">Small place where they serve coffee and food such as pastries</span></p>
<p><br></p>
<p><strong>Comment procède-t-on pour suggérer des codes IBC?</strong></p>
<div class="ol-font-size-medium">
<ol type="1">
<li>On obtient un <strong>embedding</strong> représentant la <strong>description d’entreprise cible</strong> en utilisant notre modèle fine-tuné.</li>
<li>On a préalablement fait de même pour les <strong>136 000 entreprises</strong> de notre jeu de données.</li>
<li>On calcule la <strong>distance</strong> entre l’<strong>entreprise cible</strong> et toutes les <strong>entreprises de notre jeu de données</strong>.</li>
<li>On trouve les <strong>k entreprises les plus proches</strong> (algorithme des <span class="math inline">\(k\)</span> plus proches voisins).</li>
<li>On suggère les <strong>codes les plus fréquents</strong> dans les <span class="math inline">\(k\)</span> entreprises voisines.</li>
</ol>
</div>
<p><img data-src="images/sbert_2.png" class="absolute" style="top: 160px; right: 30px; width: 170px; "></p>
</section>
<section id="sélecteur-de-codes-ibc-8" class="slide level2">
<h2>Sélecteur de codes IBC</h2>
<h3 id="application-shiny"><a href="https://rstudiotest.cgic.ca/ibc_code_selector_app/">Application Shiny</a></h3>
<!-- ![](images/app_cap.png){.absolute width=350 top=170 left=0} -->

<img data-src="images/app_cap.png" width="420" class="r-stretch"></section>
<section id="sélecteur-de-codes-ibc-9" class="slide level2" data-visibility="uncounted">
<h2>Sélecteur de codes IBC</h2>
<h3 id="architecture-de-bert-une-pile-dencodeurs-transformer">Architecture de BERT: une pile d’encodeurs « transformer »</h3>
<ul>
<li>BERT est un réseau de neurones composé de 12 ou 24 modules de type «&nbsp;transformer&nbsp;».</li>
<li>BERT « base »: 110 millions de paramètres.</li>
</ul>
<p><span class="absolute" style="top: 650px; left: 50px; ">Transformer (ENCODER)</span></p>
<p><img data-src="images/transformer-encoder.png" class="absolute" style="top: 265px; left: 50px; width: 200px; "></p>
<p><img data-src="images/bert-base-bert-large-encoders.png" class="absolute" style="top: 240px; left: 500px; width: 700px; "></p>
<aside class="notes">
<ul>
<li>L’architecture de BERT ressemble à ça. En gros, c’est un pile de blocs « transformer », plus précisément la partie « encodeuse » seulement.</li>
<li>La version de base contient 12 de ces blocs, tandis que la grande version en a 24.</li>
<li>Donc un bloc transformer, ça ressemble à ça. En gros, ça reçoit un input et ça va le passer à travers plusieurs fonctions mathématiques, dont l’attention multi-tête, qui est la clé pour comprendre le contexte de mots (je vais parler du mécanisme d’attention dans la prochaine slide).</li>
<li>Donc ce que le modèle fait en gros, c’est qu’il va partir d’un embedding fixe non-contextualisé (disons le embedding du mot « apple ») qu’il va passer à travers tous les blocs transformer pour obtenir un embedding de « apple » contextualisé.</li>
<li>Et le rôle des blocs transformers en fait, c’est de modifier le embedding de « apple » en utilisant les embeddings de tous les mots qui sont autour du mot « apple ».</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-10" class="slide level2" data-visibility="uncounted">
<h2>Sélecteur de codes IBC</h2>
<h3 id="mécanisme-dattention-permet-de-contextualiser-les-embeddings">Mécanisme d’attention: permet de contextualiser les embeddings</h3>
<div class="columns">
<div class="column" style="width:40%;">
<p><img data-src="images/attention.png" style="width:80.0%"></p>
</div><div class="column" style="width:60%;">
<p><br> <br> <img data-src="images/attention-luis.png" style="width:100.0%"></p>
</div></div>
<aside class="notes">
<ul>
<li>Le mécanisme d’attention, ça a été développé en 2017 dans l’article « Attention is all you need », et c’est grâce à ça qu’on a aujourd’hui des grands modèles de langage comme BERT, GPT, Llama ou Gemini.</li>
<li>En plus de bien capturer le contexte des mots, c’est une architecture qui est hautement parallélisable et qui permet donc d’entrainer rapidement les modèles si on a un GPU.</li>
<li>Donc comme je vous disais, c’est le mécanisme d’attention dans le transformer qui permet de modifier les embeddings des mots en utilisant les embeddings des mots voisins, et ça fait ça en utilisant un mécanisme assez complexe.</li>
<li>Donc supposons qu’on a un embedding non-contextualisé pour le mot « apple ». C’est un peu tannant, parce que « apple » peut désigner soit le fruit, soit la compagnie.</li>
<li>Ce que l’attention fait, c’est qu’elle va faire bouger l’embedding de « apple » en utilisant les mots autour.</li>
<li>Par exemple, dans la phrase « please buy me an apple and an orange », on a le mot « orange » qui va tirer le mot « apple » vers lui, ce qui va nous créer un embedding de « apple » spécialement fait pour cette phrase.</li>
<li>De la même manière, dans la phrase « apple unveiled the new phone », l’embedding de « apple » va être tiré vers l’embedding du mot « phone », et donc dans cette phrase, « apple » a plus de chance d’être interprété comme étant la compagnie Apple.</li>
<li>Il faut noter que « apple » (ainsi que tous les autres mots dans la fenêtre de contexte) va être influencé par tous les autres mots dans la fenêtre de contexte.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-11" class="slide level2" data-visibility="uncounted">
<h2>Sélecteur de codes IBC</h2>
<h4 id="sentence-bert-modifier-bert-pour-encoder-des-phrases-au-lieu-des-mots">Sentence-BERT: modifier BERT pour encoder des phrases au lieu des mots</h4>
<div class="ul-font-size-medium">
<ul>
<li>Architecture <strong>siamoise</strong> à l’entrainement utilisant un modèle <strong>BERT pré-entrainé</strong> (les poids sont identiques dans les 2 blocs BERT).</li>
<li>La couche de <strong>pooling</strong> permet d’obtenir un embedding de phrase à partir des embeddings de mots.</li>
<li>Entrainé sur le corpus <a href="#/id-SNLI">SNLI</a>: 570 000 paires de phrases annotées <span style="color:#A50E0E;"><strong>contradiction</strong></span>, <span style="color:#0D652D;"><strong>implication</strong></span> ou <span style="color: #a8aabc;"><strong>neutre</strong></span>.</li>
</ul>
</div>
<div class="columns">
<div class="column" style="text-align: center;">
<p><span style="text-decoration: underline;">À l’entrainement</span></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/sbert_1.png" class="quarto-figure quarto-figure-center" width="300"></p>
</figure>
</div>
</div><div class="column" style="text-align: center;">
<p><span style="text-decoration: underline;">À l’inférence</span></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/sbert_2.png" class="quarto-figure quarto-figure-center" width="130"></p>
</figure>
</div>
</div></div>
<p><span class="absolute" style="font-size: 17px;left: 50%; bottom: -30px; ">Figures tirées de <a href="https://www.oreilly.com/library/view/hands-on-large-language/9781098150952/">Hands-On Large Language Models – Jay Alammar et Maarten Grootendorst</a>»</span></p>
<aside class="notes">
<ul>
<li><p>Donc ça nous amène à SBERT, qui est une modification de BERT pour faire des embeddings de phrases.</p></li>
<li><p>C’est un réseau siamois (à l’entrainement) qui contient 2 modèles BERT avec les poids liés (en fait, c’est 2 copies du même modèle).</p></li>
<li><p>On a une couche de pooling qui permet de transformer les embeddings de mots en embedding de phrase.</p></li>
<li><p>Donc on prend BERT pré-entrainé et la couche de pooling qu’on arrange en un réseau siamois, et on va aller entrainer cette architecture sur un jeu de données de paires de phrases annotées contradiction, implication, ou neutre.</p></li>
<li><p>Donc on prend chacune des 2 phrases, qu’on va passer au modèle BERT. Ensuite, la sortie de BERT va être donnée à la couche de pooling, qui va nous sortir un embedding de phrase. Ensuite, on va concaténer les 2 embeddings en plus de la différence absolue élément par élément, et c’est ce vecteur qui va être utilisé pour la classification entre « contradiction », « implication » ou « neutre ».</p></li>
<li><p>Une fois le modèle entrainé, on peut se débarasser de l’architecture siamoise et garder seulement BERT + pooling.</p></li>
<li><p>Donc en fait, ce qui améliore les embeddings de phrase, c’est vraiment l’étape d’entrainement sur les paires de phrases.</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sélecteur-de-codes-ibc-12" class="slide level2" data-visibility="uncounted">
<h2>Sélecteur de codes IBC</h2>
<h3 id="télécharger-le-modèle-pré-entrainé">Télécharger le modèle pré-entrainé</h3>
<p><img data-src="images/codeimage-snippet_21.svg" class="absolute" style="top: 100px; left: -60px; width: 800px; "></p>
<p><img data-src="images/encode_snippet.svg" class="absolute" style="top: 100px; right: 0px; width: 600px; "></p>
<div style="margin-top:310px; font-size: 25px;">
<table class="caption-top">
<colgroup>
<col style="width: 42%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Phrase</th>
<th>dim_1</th>
<th>dim_2</th>
<th>…</th>
<th>dim_768</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>That is a happy person</td>
<td>-0.0203</td>
<td>-0.0104</td>
<td>…</td>
<td>-0.0053</td>
</tr>
<tr class="even">
<td>That is a happy dog</td>
<td>-0.0196</td>
<td>-0.0323</td>
<td>…</td>
<td>-0.0274</td>
</tr>
<tr class="odd">
<td>That is a very happy person</td>
<td>-0.0136</td>
<td>0.0043</td>
<td>…</td>
<td>-0.0054</td>
</tr>
<tr class="even">
<td>Today is a sunny day</td>
<td>-0.0075</td>
<td>-0.0023</td>
<td>…</td>
<td>0.0078</td>
</tr>
</tbody>
</table>
</div>
<p>On peut tester le modèle <a href="https://huggingface.co/sentence-transformers/all-mpnet-base-v2">ici</a>.</p>
<aside class="notes">
<ul>
<li>On peut facilement télécharger le modèle à partir du site HuggingFace en utilisant la librairie « sentence_transformers ».</li>
<li>Le modèle qu’on utilise n’est pas exactement le SBERT original, mais quelque chose de très similaire. C’est le modèle de base, donc celui avec 12 blocs transformers et 110 millions de paramètres.</li>
<li>On peut commencer à l’utiliser directement pour obtenir des embeddings de phrases avec la méthode « encode ».</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="imagerie" class="slide level2" data-visibility="uncounted">
<h2>Imagerie</h2>
<p>Estimer le coût de reconstruction des maisons.</p>
<p><video data-src="images/imagerie.mp4" width="950" controls=""><a href="images/imagerie.mp4">Video</a></video></p>
<p><span style="margin-left:60px;">Précision de +/- 50k$</span></p>
</section>
<section id="cartes-dinondations" class="slide level2" data-visibility="uncounted">
<h2>Cartes d’inondations</h2>
<p><br></p>
<p>Améliorer les cartes d’inondation fournies par JBL, car celles-ci « pensaient » que les forêt sont des blocs qui ne laissent pas passer l’eau.</p>
<div class="colums">
<div class="column" style="width:49%;">
<p>Avant</p>
<p><img data-src="images/avant.png"></p>
</div><div class="column" style="width:49%;">
<p>Après</p>
<p><img data-src="images/apres.png"></p>
</div></div>
</section>
<section id="autres-projets" class="slide level2" data-visibility="uncounted">
<h2>Autres projets</h2>
<p><br></p>
<ul>
<li>Développer un modèle de tarification télématique pour le nouveau produit d’assurance télématique.</li>
<li>Développer une application Shiny se basant sur le simulateur d’innondations pour mieux gérer notre risque de concentration.</li>
<li>Améliorer le processus des indiqués en utilisant la théorie des valeurs extrêmes pour estimer une période de retour pour les grosses réclamations.</li>
<li>« Fuzzy matching » pour l’équipe d’analytique de fraudes.</li>
</ul>
</section>
<section id="les-défis-de-lindustrie" class="slide level2" data-visibility="uncounted">
<h2>Les défis de l’industrie</h2>
<p><br> <strong>Dans aucun ordre particulier:</strong></p>
<ul>
<li>Fraude</li>
<li>Catastrophes naturelles: inondations, séismes, feux de forêt, etc.</li>
<li>Modélisation des grosses pertes</li>
<li>Assurance télématique</li>
<li>Traitement de langage naturel</li>
<li>Etc.</li>
</ul>
<p><img data-src="images/icon_flood.png" class="absolute" style="bottom: 0px; right: 10%; width: 400px; "></p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo_blue_2.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://github.com/francisduval/presentation_uqam_3_decembre_2024">https://github.com/francisduval/presentation_uqam_3_decembre_2024</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <!-- Javascript function allowing to hide footer on slides other than title slide -->

    <script type="text/javascript" charset="utf-8">

      function add_custom_footer() {

        let title_slide = document.querySelector("section#title-slide");

        let title_slide_footer = title_slide.getAttribute('data-footer');

        let footer = document.querySelector('div.footer p');

        let global_footer_text = footer.innerHTML;

    

        if (title_slide.classList.contains('present')) {

          footer.innerHTML = title_slide_footer;

        }

    

        Reveal.on( 'slidechanged' , event => {

            if (event.currentSlide.matches('#title-slide')) {

              footer.innerHTML = global_footer_text;

            } else {

              footer.innerHTML = title_slide_footer;

            }

          });

      };

    

      window.addEventListener("load", (event) => {

        add_custom_footer();

      });

    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copié");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copié");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>